### ISSUE TITLE
compile instructions

### ISSUE THREAD

**Issue by mabod** [prozumr/RLOTTO2#1]
Hi,

can you provide a README with compile instructions so that I can test it on Linux?

**Comment by prozumr** [comment]
I'm not yet really maintaining a README since this is planned for a later state of the project. However I can provide simple compile instructions:

gcc rlotto.c t_select.c t_add.c t_evaluate.c t_delete.c settings.c t_common.c -o rlotto.exe

Mandatory source files are also rlotto.h and version.h. Make sure to download them as well in your local source code directory.

At this state I do not recommend to start creating another branch/fork or to use this version for any modification for your own purposes since I am currently in process to change some of the basic logic quite a lot - e.g. for removing bonus numbers completely based on "new" lottery  rules from 2013. However you can pull the files and try compilation on Linux. I am curious if this will work flawlessly (My only concern would be I/O for filesystem but I just used relative path names so it should work with Linux/Unix). I am preparing a new commit - hopefully ready by beginning of next week.
